services:
  pgAdmin:
    image: dpage/pgadmin4:8.1
    restart: on-failure:3
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
    profiles:
      - e2e
      - db

  postgres:
    image: postgres:16.0-bookworm
    restart: on-failure:3
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_EXPOSED_PORT}:5432"
    profiles:
      - e2e
      - db

  app:
    image: awesome-sql-orm-app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=main
    env_file:
      - .env
    logging:
      driver: json-file
    profiles:
      - e2e

volumes:
  postgres:
