services:
  postgres:
    image: postgres:16.0-bookworm
    restart: on-failure:3
    ports:
      - "$POSTGRES_EXPOSED_PORT:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env

volumes:
  postgres:
